### ISSUE TITLE
Shiny HtmlWidget wrapper?

### ISSUE THREAD

**Issue by wyu** [calipho-sib/nextprot-viewers#4]
Hi, is there a plan to produce a version of your Javascript viewer for Shiny app? In particular, I'd love to use the sequence coverage viewer, and track view of the protein.

Thanks!
Wen

**Comment by ddtxra** [comment]
Dear Wen,
Unfortunately not at the moment... But one is free to fork the project and create a wrapper for Shiny app if that sounds feasible.
